# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andrea Di Lisio
title: Senior Software Engineer
email: andrea.dilisio91@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: AndreaDili
github_username:  dili91
stackoverflow_username: "5779776"
linkedin_username: andrea-di-lisio

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "G-LRQXR3467B"
gtag: "G-LRQXR3467B"
# google_analytics: "G-LRQXR3467B"

# About Section
about_title: Whoami
about_profile_image: images/profile.jpeg
about_content: |
  My name is Andrea and I'm currently working as senior software engineer for TrueLayer.
  
  I dedicate most of my time at designing and building APIs and internal services,
  as well as DevOps tasks. The rest of my day goes to technical briefs, code reviews, mentoring and interviews.
  
  I'm a fluent `Java` developer, but I'm not obsessed with it. I see my coding skills as a tool to turn great ideas into amazing products and I'm very keen to expand my skillset on a daily basis.
  
  At TrueLayer I've been playing quite a lot with `C#/.NET Core` and `Rust` recently. I'm intrigued by `DevOps` and I've been working for a long time now with `AWS`,
  `Terraform` and `Kubernetes`.
  
  Over the last years I've been focussing in the payments business area, ranging from e-commerce to carrier billing to online banking.

  
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: TrueLayer
        link: truelayer.com
        sub_title: Senior Software Engineer
        caption: April 2020 - Present
        description: |
          I initially joined the UK & Ireland connectivity team as a senior software engineer. My main resposibilities involved 
          connecting new banks to our platform and building internal services to collect user data about accounts and transactions or initiate
          payments via _Open Banking_ services. I dedicated a big chunk of my time to the migration of production services to a completely new Kubernetes cluster on the AWS cloud.

          In the last months I joined a product team which is responsibile of building a recurring payments product based on _Open Banking_ and UK Direct debits.
          After an initial phase mostly made of technical discovery, technical design and planning, i'm now more focussed on the building phase of our product.
          
          I mostly work in Rust, C# and with Kubernetes resources. In my _spare time_ I'm actively contributing to a Java SDK which will be made available in future to our customers 
          as an easy way to interact with our new payments APIs.
      - layout: left
        title: Onebip / DIMOCO
        link: https://dimoco.eu/carrierbilling/
        link_text: dimoco.eu
        sub_title: Devops, Senior Software Engineer
        caption: May 2019 - April 2020
        description: |
          Working from Milan for DIMOCO's carrier billing department, as software engineer in a QA and DevOps team.
          When I joined the company, the payments product team was fully committed at replacing a legacy payment infrastructure with a new one based on microservices,
          which aimed to be way more scalable and extensible than the previous one. 
          I was responsible of maintaining and evolving an internal testing infrastructure, meant to suport this transition with the help of end-to-end tests on
          mobile devices connected to physical servers across different countries in Europe. 
          
          During the last months of my experience I transitioned to the payments product team, where I implemented a translation layer so that our live customers
          could interact with the new infrastructure without any changes to their legacy integration.

          I mostly worked with Java on the product team and used Groovy and bash as scripting language when taking care of Devops tasks.
      - layout: left
        title: Vipera Plc / Fabrick
        link_text: fabrick.com
        link: https://www.fabrick.com/acquisition-of-vipera-plc/
        sub_title: Software Engineer, Technical lead
        caption: January 2017 - April May 2019
        description: |
          I joined Vipera as a backend engineer. I was mostly working on projects for retail and banking customers built on Vipera's
          banking platform based on Java OSGi. Though I was not part of the product team, I was constantly in touch with it as I had
          to know the product very well, and also take care of specific customers customizations (i.e. loyalty programs,
          ecommerce, proximity marketing) which required a deep understanding of our product's internals.

          in 2018 I accepted to transition to a technical lead position on a project for a banking customer in the UAE. I was working
          alongside a project manager and a business analyst, supervisioning the work of a team of 8 engineers, working both in Milan and remotely from India.
          Our objective was to replace the existing online banking platform with a new one based on Vipera's banking solution.

          It was my first experience as technical lead, and I had the chance to learn a lot both from a technical and human/soft-skill perspective.
          I really enjoyed exploring this new role and its associated responsibilities, both in the happy and the stressful times.
          
      - layout: left
        title: Codd&Date
        link: www.codd-date.com
        sub_title: Software Engineer
        caption: November 2013 - January 2017
        description: |
          My first working experience. I've been working for the first 3 months as intern, and I had the chance to experiment both
          on frontend and backend software development. It was a great opportunity for me to understand my desired career path.
          I got my hands dirty initially on mobile hybrid development, then I slowly transitioned to backend development first with 
          a bit of .NET and eventually Java. Here is where I started seeing live customer on the AWS platform and had fun solving 
          my first performance and scalability headaches with cloud services. Worked mainly for retail and banking customers.
  - title: Courses and certifications
    layout: list
    content:
      - layout: left
        title: The Principal Developer
        link_text: principal.dev
        link: https://principal.dev/
        caption: Septemper 2021
        description: |
          While working at TrueLayer I had the luck to remotely attend a 2 day course with <a href="https://sizovs.net/" target="_blank">Eduards Sizovs</a> named
          _The Principal Developer_. The course is meant for experienced software developers or leads interested
          in exploring or strengthening team leadership related skills.

          Certificate id: <a href="https://certs.devchampions.com/RHMN9SF7PF/" target="_blank">RHMN9SF7PF</a>
      - layout: left
        title: Distributed Systems Design Fundamentals
        link_text: learn.particular.net
        link: https://learn.particular.net/courses/distributed-systems-design-fundamentals-online
        caption: July 2021
        description: |
          Attended and loved this online course by <a href="https://udidahan.com/" target="_blank">Udi Dahan</a> on system design fundamentals. Looking forward to attend the advanced course
          whenever I can.  

          Certificate id: <a href="https://www.credential.net/5787fac1-76d4-4706-ba1e-12647b7c0a63" target="_blank">5787fac1-76d4-4706-ba1e-12647b7c0a63</a>    
      - layout: left
        title: Microservices Fundamentals
        link_text: coursera.org
        link: https://www.coursera.org/
        caption: January 2020
        description: |
          I was looking for a thereotical introduction to microservices and their implications on team work and I found this online
          course by IBM on Coursera. 

          Certificate id: <a href="https://www.credly.com/badges/f09fa5c4-a7c5-496f-990d-14ec5f5c8be3" target="_blank">f09fa5c4-a7c5-496f-990d-14ec5f5c8be3</a>
      - layout: left
        title: Certified Kubernetes Application Developer (CKAD)
        link_text: cncf.io
        link: https://www.cncf.io/certification/ckad/
        caption: December 2019
        description: |
          I had been working with Docker and Kubernetes for a long time and I felt like it was time to strenghten my knowledge and proficiency with that.
          Completed this course while working as DevOps for DIMOCO, scoring a result of 93/100.

          Certificate id: <a href="https://www.credly.com/badges/690c3b28-caec-4a2b-aa5c-d9a20922dbbd" target="_blank">CKAD-1900-002224-0100</a>
      - layout: left
        title: IBM Blockchain Foundation for Developers
        link_text: coursera.org
        link: https://www.coursera.org/
        caption: June 2018
        description: |
          As I was hearing the term _Blockchain_ more and more often, I wanted to know more about the theory behind it and its possible applications.
          Attended this brief course online out of personal curiosity.

          Certificate id: <a href="https://www.coursera.org/account/accomplishments/verify/FZ2TUU4WGPBK" target="_blank">FZ2TUU4WGPBK</a>
      - layout: left
        title: MongoDB for Java Developers (M220J)
        link_text: university.mongodb.com
        link: https://university.mongodb.com/courses/M220J/about
        caption: June 2015
        description: |
          While working at Codd&Date I dipped my nose into MongoDb and the NoSQL world for the first time. This course was a very nice
          introduction to NoSQL in general and on how to efficiently use Mongo with the Java language.
  
  - title: Education
    layout: list
    content:
      - layout: left
        title: Politecnico di Milano
        caption: 2010 - 2013
        sub_title: Computer engineering
        description: | 
          I attended Politecnico's Computering engineering course after high school. On my third and last year I converted an optional exam into 
          an internship of 3 months which I completed in Codd&Date. Soon after that I was offered a job and I decided to prioritize my 
          working experience over my studies. Eventually that move led to me not completing my last bachelor exams, but I'm fine with it.
          Nevertheless these 3 years were crucial to understand what I wanted from my career and I see those as a fundamental step for my 
          growht and who I am right now.
      - layout: left
        title: Liceo scientifico Vittorio Veneto
        caption: 2005 - 2010
        sub_title: Scientific high school  
        description: | 
          I attended a scientific high school, with courses in both english and german (which to be honest I completely forgot). 
          Nothing much to add. Fun times! :)
            
  - title: A Little More About Me
    layout: text
    content: |
      > If you feel like you're the dumbest person in the room, you're in the correct room.

      The above one is one of my favorite mantra: I love to sorround myself with smart and motivated people because it's always a learning and 
      humbling experience at the same time. This is exaclty what's happening in TrueLayer, where we created an amazing movement and an extremely ambitious mission which is 
      _Opening up finance_, that is streamline as much as we can the access to banking data and payments. 
      
      As mentioned in my intro I'm not scared at all by learning new languages or skills in general as long I can see motivation and commitment around me. 
      I see them as an investment and a way to train my curiosity. I love being part of a community, hanging around the office spaces and travelling - pandemic permitting.  
  
      In addition to what I do for TrueLayer I like taking care of extra projects in my extra time. I try to work on open source projects 
      whenever I can - some of my contributions are available on my Github profile.
      I've been recently helping a few small startups in Milan on either cloud infrastructure optimizations or with technical consultancy in general.

      When I'm not using my laptop I like doing sports, football, padel, ski and workouts being my favourites.
      I love living my city spaces either on my own or along with friends: cinema, parks, pubs, wineries and restaurants.
      I like listening to (a lot of) music, especially rock, blues and soul music. I'm a self-taught guitar player but i'm not planning to organize a concert anytime soon :) 

      I recently re-discovered the joy of reading and I try to read as much as I can during the year. 
      Below a few titles I've been (or I am) recently enjoying:
      - <a href="https://www.goodreads.com/book/show/53916142-a-life-on-our-planet">A Life on Our Planet</a>, David Attenborough
      - <a href="https://www.goodreads.com/book/show/6480781-open">Open</a>, Andre Agassi
      - <a href="https://www.goodreads.com/book/show/52647113-apropos-of-nothing">Apropos of Nothing</a>, Woody Allen
      - <a href="https://www.goodreads.com/book/show/34890015-factfulness">Factfulness</a>, Hans Rosling
      - <a href="https://www.goodreads.com/book/show/33600.Shantaram">Shantaram</a>, Gregory David Roberts
      - <a href="https://www.goodreads.com/book/show/39996759-a-philosophy-of-software-design">A Philosophy of Software Design</a>, John Ousterhout
      - <a href="https://www.goodreads.com/book/show/23463279-designing-data-intensive-applications">Designing Data-Intensive Applications</a>, Martin Kleppmann
      - <a href="https://www.goodreads.com/book/show/25550614-programming-rust">Programming Rust: Fast, Safe Systems Development</a>, Jim Blandy
      - <a href="https://www.goodreads.com/book/show/55730109-zero-to-production-in-rust">Zero To Production In Rust</a>, Luca Palmieri
      


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
